name: Build
on:
  workflow_call:
    inputs:
      project_name:
        description: 'Porject name (required)'
        required: true
        type: string
      skip-dev:
        description: 'Skip dev'
        required: false
        default: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Cache........'
      - run: echo 'Checkout.....'
      - run: echo 'Building.....'
      - run: echo 'after script if master'