name: Main

on: [push]

  strategy:
    matrix:
      project:
        - siag
        - ocs
        - traefik1
        - traefik2
jobs:
#  build:
#    uses: ./.github/workflows/build.yml

  release:
    #needs: build
    uses: ./.github/workflows/release.yml
    with:
      project_name: ${{ matrix }}
      skip-dev: false
