name: Main

on: [push]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project_name: build
      skip-dev: false

  release:
    #needs: build
    uses: ./.github/workflows/release.yml
    with:
      project_name: MY_PROJECT_NAME
      skip-dev: false
