name: Main

on: [push]

jobs:
  build:
    steps:
      uses: ./.github/workflows/build.yml
      with:
        my_sec: ${{ secrets.MY_SEC }}

  release:
    needs: build
    uses: ./.github/workflows/release.yml

